################################################################
#
# $Id:$
#
# $Log:$
#

# ifeq ($(V),1)
# 	VB=''
# else
# 	VB=@
# endif


ROOT := $(abspath $(dir $(abspath $(lastword $(MAKEFILE_LIST))))..)

ELOS_ROOT := $(abspath $(ROOT)/../elos)
PRISM_ROOT := $(abspath $(ROOT)/../elos/apps/prism)

SILENT := @
TOOLCHAIN := 
# TOOLCHAIN := x86_64-elf-
CC := $(TOOLCHAIN)gcc  # gcc or g++
AS := $(TOOLCHAIN)as  # gcc or g++
# CFLAGS+=-DFEATURE_SOUND $(SDL_CFLAGS)
CFLAGS+= 
LDFLAGS+=
LIBS+=

CFLAGS += -g -O0   -nostdlib -nostartfiles -nodefaultlibs -fno-asynchronous-unwind-tables -fno-exceptions -fno-stack-protector -Wl,--no-warn-execstack -Wno-builtin-declaration-mismatch
CFLAGS += -I $(ELOS_ROOT)/kernel/src -I $(ELOS_ROOT)/kernel/include -I $(PRISM_ROOT)/include -I $(ELOS_ROOT)/apps/std

# subdirectory for objects
OBJDIR ?= int
OUTPUT ?= doom

SRC_DIRS += \
	$(ELOS_ROOT)/kernel/src/elos/common \
	$(PRISM_ROOT)/src/prism_client/prism_client.c \
	$(ELOS_ROOT)/apps/std \
	#

SRC_ELOS := \
	$(foreach dir,$(SRC_DIRS),$(shell find $(dir) \( -name '*.c' -o -name '*.s' \) ))

	

SRC_DOOM := dummy.o am_map.o doomdef.o doomstat.o dstrings.o d_event.o d_items.o d_iwad.o d_loop.o d_main.o d_mode.o d_net.o f_finale.o f_wipe.o g_game.o hu_lib.o hu_stuff.o info.o i_cdmus.o i_endoom.o i_joystick.o i_scale.o i_sound.o i_system.o i_timer.o memio.o m_argv.o m_bbox.o m_cheat.o m_config.o m_controls.o m_fixed.o m_menu.o m_misc.o m_random.o p_ceilng.o p_doors.o p_enemy.o p_floor.o p_inter.o p_lights.o p_map.o p_maputl.o p_mobj.o p_plats.o p_pspr.o p_saveg.o p_setup.o p_sight.o p_spec.o p_switch.o p_telept.o p_tick.o p_user.o r_bsp.o r_data.o r_draw.o r_main.o r_plane.o r_segs.o r_sky.o r_things.o sha1.o sounds.o statdump.o st_lib.o st_stuff.o s_sound.o tables.o v_video.o wi_stuff.o w_checksum.o w_file.o w_main.o w_wad.o z_zone.o w_file_stdc.o i_input.o i_video.o doomgeneric.o doomgeneric_elos.o mus2mid.o


SRC_DOOM := $(addprefix $(ROOT)/doomgeneric/, $(SRC_DOOM))

# OBJS += $(addprefix $(OBJDIR)/, $(SRC_DOOM))



# SRC_DIRS := \
# 	$(ROOT)/doomgeneric \

# SRC_FILES := \
# 	$(foreach dir,$(SRC_DIRS),$(shell find $(dir) \( -name '*.c' -o -name '*.s' \) ))

SRC_FILES := $(SRC_DOOM) $(SRC_ELOS) 

OBJ_FILES := \
	$(patsubst $(ROOT)/%.c,$(OBJDIR)/%.o,$(SRC_FILES)) \

OBJ_FILES := $(patsubst $(ROOT)/%.s,$(OBJDIR)/%.o,$(OBJ_FILES))
# OBJ_FILES := $(patsubst $(INT_DIR)/%.s,$(INT_DIR)/%.o,$(OBJ_FILES))

# DEP_FILES := $(patsubst %.o,%.d,$(OBJ_FILES))

OBJS = $(OBJ_FILES)

all:	 $(OUTPUT)

clean:
	rm -rf $(OBJDIR)
	rm -f $(OUTPUT)
	rm -f $(OUTPUT).gdb
	rm -f $(OUTPUT).map

$(OUTPUT):	$(OBJS)
	@#echo [Linking $@]
	$(SILENT) mkdir -p $(@D)
	$(SILENT)$(CC) $(CFLAGS) $(LDFLAGS) $(OBJS) \
	-o $(OUTPUT) $(LIBS)

$(OBJS): | $(OBJDIR)

$(OBJDIR):
	mkdir -p $(OBJDIR)

$(OBJDIR)/%.o:	%.c
	@echo [Compiling $<]
	$(SILENT) mkdir -p $(@D)
	$(SILENT)$(CC) $(CFLAGS) -c $< -o $@

$(OBJDIR)/%.o:	%.s
	@echo [Compiling $<]
	$(SILENT) mkdir -p $(@D)
	$(SILENT) $(AS)  -c $< -o $@

print:
	@echo OBJS: $(OBJS)

